// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lPnR5hdeHCnoMgZnRgOSkie6Cu1xDFg',
    appId: '1:249278130119:web:ff810fbfba25b4687b1be2',
    messagingSenderId: '249278130119',
    projectId: 'mealordring',
    authDomain: 'mealordring.firebaseapp.com',
    storageBucket: 'mealordring.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVAiQQaS7hV5shTTngPx-cdXOR6VDXfRs',
    appId: '1:249278130119:android:d27a02daab0dca7f7b1be2',
    messagingSenderId: '249278130119',
    projectId: 'mealordring',
    storageBucket: 'mealordring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw4mUiTJeCg1EkH5ritjzQ7fBE23bSs40',
    appId: '1:249278130119:ios:5f49d97e3c4346297b1be2',
    messagingSenderId: '249278130119',
    projectId: 'mealordring',
    storageBucket: 'mealordring.appspot.com',
    iosBundleId: 'com.example.mealOrdering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw4mUiTJeCg1EkH5ritjzQ7fBE23bSs40',
    appId: '1:249278130119:ios:5f49d97e3c4346297b1be2',
    messagingSenderId: '249278130119',
    projectId: 'mealordring',
    storageBucket: 'mealordring.appspot.com',
    iosBundleId: 'com.example.mealOrdering',
  );
}
